linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports

run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false
  exclude:
    - "Error return value of .(Close|Stop|Quit) is not checked"
